# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build_web:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - node/install:
         install-npm: true
         node-version: 16.13.0
      - run: node --version
      - restore_cache:
          keys:
            - node-modules-cache
      - run:
          name: export path
          command: echo 'export PATH="$PATH:/usr/local/bin"' >> $BASH_ENV
      - run:
          name: Install Dependencies npm
          command: cd examples/alan-example-integration-angular && npm install
      - run:
          name: Run build
          command: cd examples/alan-example-integration-angular && npm run build
      - save_cache:
          key: node-modules-cache
          paths:
            - ./node_modules
            
workflows:
  version: 2.1
  build-web:
    jobs:
      - build_web
